INSERT INTO marilyn.initials(sound,"group",pinyin)
VALUES ('∅', 'a', ''),
     ('b', 'a', 'b'),
     ('p', 'a', 'p'),
     ('m', 'a', 'm'),
     ('f', 'a', 'f'),
     ('d', 'a', 'd'),
     ('t', 'a', 't'),
     ('n', 'a', 'n'),
     ('l', 'a', 'l'),
     ('g', 'a', 'g'),
     ('k', 'a', 'k'),
     ('h', 'a', 'h'),
     ('zh', 'a', 'zh'),
     ('ch', 'a', 'ch'),
     ('sh', 'a', 'sh'),
     ('r', 'a', 'r'),
     ('z', 'a', 'z'),
     ('c', 'a', 'c'),
     ('s', 'a', 's'),
     ('∅', 'i', 'y'),
     ('b', 'i', 'bi'),
     ('p', 'i', 'pi'),
     ('m', 'i', 'mi'),
     ('f', 'i', 'fi'),
     ('d', 'i', 'di'),
     ('t', 'i', 'ti'),
     ('n', 'i', 'ni'),
     ('l', 'i', 'li'),
     ('j', 'i', 'ji'),
     ('q', 'i', 'qi'),
     ('x', 'i', 'xi'),
     ('∅', 'u', 'w'),
     ('b', 'u', 'bu'),
     ('p', 'u', 'pu'),
     ('m', 'u', 'mu'),
     ('f', 'u', 'fu'),
     ('d', 'u', 'du'),
     ('t', 'u', 'tu'),
     ('n', 'u', 'nu'),
     ('l', 'u', 'lu'),
     ('g', 'u', 'gu'),
     ('k', 'u', 'ku'),
     ('h', 'u', 'hu'),
     ('zh', 'u', 'zhu'),
     ('ch', 'u', 'chu'),
     ('sh', 'u', 'shu'),
     ('r', 'u', 'ru'),
     ('z', 'u', 'zu'),
     ('c', 'u', 'cu'),
     ('s', 'u', 'su'),
     ('∅', 'ü', 'y'),
     ('n', 'ü', 'nü'),
     ('l', 'ü', 'lü'),
     ('j', 'ü', 'jü'),
     ('q', 'ü', 'qü'),
     ('x', 'ü', 'xü')
ON CONFLICT DO NOTHING;
--;;
INSERT INTO marilyn.finals(sound,pinyin)
VALUES  ('-','-'),
        ('i', 'i'),
        ('a', 'a'),
        ('e', 'e'),
        ('ê', 'ê'),
        ('ai', 'ai'),
        ('ei', 'ei'),
        ('ao', 'ao'),
        ('ou', 'ou'),
        ('an', 'an'),
        ('en', 'en'),
        ('ang', 'ang'),
        ('eng', 'eng'),
        ('er', 'er')
ON CONFLICT DO NOTHING;
