INSERT INTO marilyn.initials(sound,"group",pinyin)
VALUES ('∅', 'a', ''),
     ('b', 'a', 'ba'),
     ('p', 'a', 'pa'),
     ('m', 'a', 'ma'),
     ('f', 'a', 'fa'),
     ('d', 'a', 'da'),
     ('t', 'a', 'ta'),
     ('n', 'a', 'na'),
     ('l', 'a', 'la'),
     ('g', 'a', 'ga'),
     ('k', 'a', 'ka'),
     ('h', 'a', 'ha'),
     ('zh', 'a', 'zha'),
     ('ch', 'a', 'cha'),
     ('sh', 'a', 'sha'),
     ('r', 'a', 'ra'),
     ('z', 'a', 'za'),
     ('c', 'a', 'ca'),
     ('s', 'a', 'sa'),
     ('∅', 'i', 'y'),
     ('b', 'i', 'bi'),
     ('p', 'i', 'pi'),
     ('m', 'i', 'mi'),
     ('f', 'i', 'fi'),
     ('d', 'i', 'di'),
     ('t', 'i', 'ti'),
     ('n', 'i', 'ni'),
     ('l', 'i', 'li'),
     ('j', 'i', 'ji'),
     ('q', 'i', 'qi'),
     ('x', 'i', 'xi'),
     ('∅', 'u', 'w'),
     ('b', 'u', 'bu'),
     ('p', 'u', 'pu'),
     ('m', 'u', 'mu'),
     ('f', 'u', 'fu'),
     ('d', 'u', 'du'),
     ('t', 'u', 'tu'),
     ('n', 'u', 'nu'),
     ('l', 'u', 'lu'),
     ('g', 'u', 'gu'),
     ('k', 'u', 'ku'),
     ('h', 'u', 'hu'),
     ('zh', 'u', 'zhu'),
     ('ch', 'u', 'chu'),
     ('sh', 'u', 'shu'),
     ('r', 'u', 'ru'),
     ('z', 'u', 'zu'),
     ('c', 'u', 'cu'),
     ('s', 'u', 'su'),
     ('∅', 'uv', 'y'),
     ('n', 'uv', 'nuv'),
     ('l', 'uv', 'luv'),
     ('j', 'uv', 'juv'),
     ('q', 'uv', 'quv'),
     ('x', 'uv', 'xuv')
ON CONFLICT DO NOTHING;
--;;
INSERT INTO marilyn.finals(sound,pinyin)
VALUES  ('-','-'),
        ('i', 'i'),
        ('a', 'a'),
        ('e', 'e'),
        ('ê', 'ê'),
        ('ai', 'ai'),
        ('ei', 'ei'),
        ('ao', 'ao'),
        ('ou', 'ou'),
        ('an', 'an'),
        ('en', 'en'),
        ('ang', 'ang'),
        ('eng', 'eng'),
        ('er', 'er')
ON CONFLICT DO NOTHING;
