CREATE TABLE marilyn.actors (
    id BIGSERIAL PRIMARY KEY,
    name TEXT NOT NULL ,
    note TEXT,
    image TEXT,
    initial_id BIGINT REFERENCES marilyn.initials(id),
    user_id BIGINT REFERENCES public.users(id),
    created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT actors_unique_for_user UNIQUE (initial_id, user_id),
    CONSTRAINT actors_unique_image_for_user UNIQUE (image, user_id)
);

--;;


INSERT INTO marilyn.actors(initial_id,name,image,user_id)
VALUES (1, 'Ares', 'https://hanzihack.com/media/actors/1/a.jpg',1),
       (2, 'Bellona', 'https://hanzihack.com/media/actors/1/b.jpg',1),
       (3, 'Poseidon', 'https://hanzihack.com/media/actors/1/p.jpg',1),
       (4, 'Mercury', 'https://hanzihack.com/media/actors/1/m.jpg',1),
       (5, 'Freya', 'https://hanzihack.com/media/actors/1/f.jpg',1),
       (6, 'Daji', 'https://hanzihack.com/media/actors/1/d.jpg',1),
       (7, 'Thanatos', 'https://hanzihack.com/media/actors/1/t.jpg',1),
       (8, 'Neith', 'https://hanzihack.com/media/actors/1/n.jpg',1),
       (9, 'Loki', 'https://hanzihack.com/media/actors/1/l.jpg',1),
       (10, 'Geb', 'https://hanzihack.com/media/actors/1/g.jpg',1),
       (11, 'Kali', 'https://hanzihack.com/media/actors/1/k.jpg',1),
       (12, 'Hades', 'https://hanzihack.com/media/actors/1/h.jpg',1),
       (13, 'Zhong Kui', 'https://hanzihack.com/media/actors/1/zh.jpg',1),
       (14, 'ChangE', 'https://hanzihack.com/media/actors/1/ch.jpg',1),
       (15, 'Erlang Shen', 'https://hanzihack.com/media/actors/1/sh.jpg',1),
       (16, 'Ra', 'https://hanzihack.com/media/actors/1/r.jpg',1),
       (17, 'Zeus', 'https://hanzihack.com/media/actors/1/z.jpg',1),
       (18, 'Cupid', 'https://hanzihack.com/media/actors/1/c.jpg',1),
       (19, 'Skadi', 'https://hanzihack.com/media/actors/1/s.jpg',1),
       (20, 'Irene RedVelvet', 'https://hanzihack.com/media/actors/1/yi.jpg',1),
       (21, 'Bol4 - Ji young', 'https://hanzihack.com/media/actors/1/bi.jpg',1),
       (22, 'Postmalone', 'https://hanzihack.com/media/actors/1/pi.jpg',1),
       (23, 'Mashmello', 'https://hanzihack.com/media/actors/1/mi.jpg',1),
       (24, 'Dua Lipa', 'https://hanzihack.com/media/actors/1/di.jpg',1),
       (25, 'Taylor Swift', 'https://hanzihack.com/media/actors/1/ti.jpg',1),
       (26, 'Nicki Minaj', 'https://hanzihack.com/media/actors/1/ni.jpg',1),
       (27, 'Lisa', 'https://hanzihack.com/media/actors/1/li.jpg',1),
       (28, 'Jisoo', 'https://hanzihack.com/media/actors/1/ji.jpg',1),
       (29, 'Shawn Mendes', 'https://hanzihack.com/media/actors/1/qi.jpg',1),
       (30, 'Sia Furler', 'https://hanzihack.com/media/actors/1/xi.jpg',1),
       (31, 'Windranger', 'https://hanzihack.com/media/actors/1/wu.jpg',1),
       (32, 'Bristleback', 'https://hanzihack.com/media/actors/1/bu.jpg',1),
       (33, 'Puck', 'https://hanzihack.com/media/actors/1/pu.jpg',1),
       (34, 'Mirana', 'https://hanzihack.com/media/actors/1/mu.jpg',1),
       (35, 'Faceless Void', 'https://hanzihack.com/media/actors/1/fu.jpg',1),
       (36, 'Drowranger', 'https://hanzihack.com/media/actors/1/du.jpg',1),
       (37, 'Tusk', 'https://hanzihack.com/media/actors/1/tu.jpg',1),
       (38, 'Naga', 'https://hanzihack.com/media/actors/1/nu.jpg',1),
       (39, 'Lina', 'https://hanzihack.com/media/actors/1/lu.jpg',1),
       (40, 'Gyro Copter', 'https://hanzihack.com/media/actors/1/gu.jpg',1),
       (41, 'Kunka', 'https://hanzihack.com/media/actors/1/ku.jpg',1),
       (42, 'Huska', 'https://hanzihack.com/media/actors/1/hu.jpg',1),
       (43, 'Jakiro', 'https://hanzihack.com/media/actors/1/zhu.jpg',1),
       (44, 'Chen', 'https://hanzihack.com/media/actors/1/chu.jpg',1),
       (45, 'Shadow Shaman', 'https://hanzihack.com/media/actors/1/shu.jpg',1),
       (46, 'Riki', 'https://hanzihack.com/media/actors/1/ru.jpg',1),
       (47, 'Zeus Dwarf', 'https://hanzihack.com/media/actors/1/zu.jpg',1),
       (48, 'Centaur', 'https://hanzihack.com/media/actors/1/cu.jpg',1),
       (49, 'Sladar', 'https://hanzihack.com/media/actors/1/su.jpg',1),
       (50, 'Ryan Reynold', 'https://hanzihack.com/media/actors/1/yu.jpg',1),
       (51, 'Keanu Reaves', 'https://hanzihack.com/media/actors/1/nuv.jpg',1),
       (52, 'Elizabeth Olsen', 'https://hanzihack.com/media/actors/1/luv.jpg',1),
       (53, 'Jenifer Lawrence', 'https://hanzihack.com/media/actors/1/juv.jpg',1),
       (54, 'Christ Hemsworth', 'https://hanzihack.com/media/actors/1/quv.jpg',1),
       (55, 'Alexandra Daddario', 'https://hanzihack.com/media/actors/1/xuv.jpg',1);


