CREATE TABLE marilyn.actors (
    id BIGSERIAL PRIMARY KEY,
    name TEXT NOT NULL ,
    image TEXT,
    initial_id BIGINT REFERENCES marilyn.initials(id),
    user_id BIGINT REFERENCES public.users(id),
    created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT actors_unique_for_user UNIQUE (initial_id, user_id),
    CONSTRAINT actors_unique_image_for_user UNIQUE (image, user_id)
);

--;;


INSERT INTO marilyn.actors(initial_id,name,image,user_id)
VALUES (1, 'Ares', 'img/smite/ares.jpg',1),
       (2, 'Bellona', 'img/smite/bellona.jpg',1),
       (3, 'Poseidon', 'img/smite/poseidon.jpg',1),
       (4, 'Mercury', 'img/smite/mercury.jpg',1),
       (5, 'Freya', 'img/smite/freya.jpg',1),
       (6, 'Daji', 'img/smite/daji.jpg',1),
       (7, 'Thanatos', 'img/smite/thanatos.jpg',1),
       (8, 'Neith', 'img/smite/neith.jpg',1),
       (9, 'Loki', 'img/smite/loki.jpg',1),
       (10, 'Geb', 'img/smite/geb.jpg',1),
       (11, 'Kali', 'img/smite/kali.jpg',1),
       (12, 'Hades', 'img/smite/hades.jpg',1),
       (13, 'Zhong Kui', 'img/smite/zhongkui.jpg',1),
       (14, 'ChangE', 'img/smite/change.jpg',1),
       (15, 'Erlang Shen', 'img/smite/erlang_shen.jpg',1),
       (16, 'Ra', 'img/smite/ra.jpg',1),
       (17, 'Zeus', 'img/smite/zeus.jpg',1),
       (18, 'Cupid', 'img/smite/cupid.jpg',1),
       (19, 'Skadi', 'img/smite/skadi.jpg',1),
       (20, 'Irene RedVelvet', 'img/singer/irene.jpg',1),
       (21, 'Bol4 - Ji young', 'img/singer/bol4.jpg',1),
       (22, 'Postmalone', 'img/singer/postmalone.jpg',1),
       (23, 'Mashmello', 'img/singer/mashmello.jpg',1),
       (24, 'Dua Lipa', 'img/singer/dualipa.jpg',1),
       (25, 'Taylor Swift', 'img/singer/taylor.jpg',1),
       (26, 'Nicki Minaj', 'img/singer/nicki.jpg',1),
       (27, 'Lisa', 'img/singer/lisa.jpg',1),
       (28, 'Jisoo', 'img/singer/jisoo.jpg',1),
       (29, 'Shawn Mendes', 'img/singer/shawn.jpg',1),
       (30, 'Sia Furler', 'img/singer/sia.jpg',1),
       (31, 'Windranger', 'img/dota/windranger.jpg',1),
       (32, 'Bristleback', 'img/dota/bristleback.jpg',1),
       (33, 'Puck', 'img/dota/pucj.jpg',1),
       (34, 'Mirana', 'img/dota/mirana.jpg',1),
       (35, 'Faceless Void', 'img/dota/void.jpg',1),
       (36, 'Drowranger', 'img/dota/drow.jpg',1),
       (37, 'Tusk', 'img/dota/tusj.jpg',1),
       (38, 'Naga', 'img/dota/naga.jpg',1),
       (39, 'Lina', 'img/dota/lina.jpg',1),
       (40, 'Gyro Copter', 'img/dota/gyro.jpg',1),
       (41, 'Kunka', 'img/dota/kunka.jpg',1),
       (42, 'Huska', 'img/dota/huska.jpg',1),
       (43, 'Jakiro', 'img/dota/jakiro.jpg',1),
       (44, 'Chen', 'img/dota/chen.jpg',1),
       (45, 'Shadow Shaman', 'img/dota/shadowshaman.jpg',1),
       (46, 'Riki', 'img/dota/riki.jpg',1),
       (47, 'Zeus Dwarf', 'img/dota/zeus.jpg',1),
       (48, 'Centaur', 'img/dota/centaur.jpg',1),
       (49, 'Sladar', 'img/dota/sladar.jpg',1),
       (50, 'Ryan Reynold', 'img/star/ryan.jpg',1),
       (51, 'Keanu Reaves', 'img/star/keanu.jpg',1),
       (52, 'Elizabeth Olsen', 'img/star/elizabeth.jpg',1),
       (53, 'Jenifer Lawrence', 'img/star/jenifer.jpg',1),
       (54, 'Christ Hemsworth', 'img/star/christ.jpg',1),
       (55, 'Alexandra Daddario', 'img/star/alexandra.jpg',1);

